name: Deploy CMS

on:
  push:
        branches: 'main'
        # Run only if there are at least one change matching the  following paths          
        paths:
          - 'apps/strapi-cms/**'
          - '.github/workflows/build-deploy-docker*'

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      environment:
        description: 'The environment used as target'
        type: choice
        required: true
        default: prod
        options:
        - prod

defaults:
  run:
    shell: bash
    working-directory: apps/strapi-cms

permissions:
  id-token: write   # This is required for requesting the JWT  
  contents: read    # This is required for actions/checkout

jobs:
  deploy:
    name: Docker CMS
    runs-on: ubuntu-latest
    continue-on-error: false
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
    
     # - name: Set up QEMU
     #   uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0

    #  - name: Set up Docker Buildx
   #     uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: eu-south-1
          ##role_to_assume: ${{ secrets.IAM_ROLE }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    #  - name: Docker image Build
    #    run: docker build -t strapi:latest .

   #   - name: Docker image Tag
   #     run: docker tag strapi:latest 713024823233.dkr.ecr.eu-south-1.amazonaws.com/strapi:latest

      - name: Login to ECR
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
            registry: 713024823233.dkr.ecr.eu-south-1.amazonaws.com
    
     # - name: Docker image Push
        #run: aws ecr get-login-password --region eu-south-1 | docker push 713024823233.dkr.ecr.eu-south-1.amazonaws.com/strapi:latest
     #   run: aws ecr get-login-password --region eu-south-1 | docker push ${{ steps.login-ecr.outputs.registry }}/strapi:latest
      
      - name: Build Push and Tag
        uses: docker/build-push-action@v4
        with:
            context: .
            file: ./Dockerfile
            push: true
            tags: 713024823233.dkr.ecr.eu-south-1.amazonaws.com/strapi:latest
            provenance: false
