on:
  push:
    branches:
      - "main" # change to the branch you wish to deploy from

permissions:
  contents: read
  pages: write
  id-token: write

defaults:
  run:
    shell: bash
    working-directory: apps/nextjs-website

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    # Manual Checkout
      - uses: actions/checkout@v4

    # Set up Node
    #  - uses: actions/setup-node@v4
    #    with:
    #      node-version: '18.x'
          
      - name: npminstall
        run: npm i

      - name: npmaudit
        run: npm audit fix --force
      
      - id: build-publish
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          path: build # change to your build folder
          #install_command: npm i
          build_command: npm run storybook
